// Core Lexical Bank across all 60 Topics (zh, pinyin, vi, word_type, topic_key, hsk_level)
// Every entry is an authentic, high-frequency item used in Vietnam <-> China communication.

const CORE_LEXICON = [
  // 1. greetings
  ['你好', 'nǐ hǎo', 'Xin chào', 'phrase', 'greetings', 'HSK 1'],
  ['您好', 'nín hǎo', 'Xin chào (kính trọng)', 'phrase', 'greetings', 'HSK 1'],
  ['早上好', 'zǎoshang hǎo', 'Chào buổi sáng', 'phrase', 'greetings', 'HSK 1'],
  ['下午好', 'xiàwǔ hǎo', 'Chào buổi chiều', 'phrase', 'greetings', 'HSK 1'],
  ['晚上好', 'wǎnshang hǎo', 'Chào buổi tối', 'phrase', 'greetings', 'HSK 1'],
  ['晚安', 'wǎn ān', 'Chúc ngủ ngon', 'phrase', 'greetings', 'HSK 1'],
  ['再见', 'zàijiàn', 'Tạm biệt', 'phrase', 'greetings', 'HSK 1'],
  ['明天见', 'míngtiān jiàn', 'Hẹn gặp lại ngày mai', 'phrase', 'greetings', 'HSK 1'],
  ['谢谢', 'xièxie', 'Cảm ơn', 'verb', 'greetings', 'HSK 1'],
  ['非常感谢', 'fēicháng gǎnxiè', 'Vô cùng cảm ơn', 'phrase', 'greetings', 'HSK 2'],
  ['不客气', 'bú kèqi', 'Đừng khách sáo', 'phrase', 'greetings', 'HSK 1'],
  ['对不起', 'duìbuqǐ', 'Xin lỗi', 'phrase', 'greetings', 'HSK 1'],
  ['没关系', 'méi guānxi', 'Không sao đâu', 'phrase', 'greetings', 'HSK 1'],
  ['请问', 'qǐngwèn', 'Xin hỏi', 'verb', 'greetings', 'HSK 1'],
  ['好久不见', 'hǎojiǔ bú jiàn', 'Lâu rồi không gặp', 'phrase', 'greetings', 'HSK 2'],
  ['欢迎光临', 'huānyíng guānglín', 'Chào mừng quý khách', 'phrase', 'greetings', 'HSK 2'],
  ['慢走', 'màn zǒu', 'Đi thong thả nhé (tiễn khách)', 'phrase', 'greetings', 'HSK 2'],
  ['请进', 'qǐng jìn', 'Mời vào', 'phrase', 'greetings', 'HSK 1'],
  ['请坐', 'qǐng zuò', 'Mời ngồi', 'phrase', 'greetings', 'HSK 1'],
  ['幸会', 'xìnghuì', 'Hân hạnh được gặp', 'phrase', 'greetings', 'HSK 3'],
  ['多多关照', 'duōduō guānzhào', 'Mong được giúp đỡ nhiều', 'phrase', 'greetings', 'HSK 3'],
  ['辛苦了', 'xīnkǔ le', 'Bạn vất vả rồi', 'phrase', 'greetings', 'HSK 3'],
  ['一路平安', 'yílù píng ān', 'Thượng lộ bình an', 'phrase', 'greetings', 'HSK 3'],
  ['祝你好运', 'zhù nǐ hǎoyùn', 'Chúc bạn may mắn', 'phrase', 'greetings', 'HSK 2'],

  // 2. pronouns
  ['我', 'wǒ', 'Tôi, mình', 'pronoun', 'pronouns', 'HSK 1'],
  ['你', 'nǐ', 'Bạn, cậu', 'pronoun', 'pronouns', 'HSK 1'],
  ['您', 'nín', 'Ngài, ông, bà (kính xưng)', 'pronoun', 'pronouns', 'HSK 1'],
  ['他', 'tā', 'Anh ấy, ông ấy', 'pronoun', 'pronouns', 'HSK 1'],
  ['她', 'tā', 'Cô ấy, chị ấy', 'pronoun', 'pronouns', 'HSK 1'],
  ['它', 'tā', 'Nó (đồ vật, con vật)', 'pronoun', 'pronouns', 'HSK 1'],
  ['我们', 'wǒmen', 'Chúng tôi, chúng ta', 'pronoun', 'pronouns', 'HSK 1'],
  ['咱们', 'zánmen', 'Chúng mình (bao gồm người nghe)', 'pronoun', 'pronouns', 'HSK 2'],
  ['你们', 'nǐmen', 'Các bạn', 'pronoun', 'pronouns', 'HSK 1'],
  ['他们', 'tāmen', 'Họ, bọn họ', 'pronoun', 'pronouns', 'HSK 1'],
  ['自己', 'zìjǐ', 'Bản thân, tự mình', 'pronoun', 'pronouns', 'HSK 2'],
  ['大家', 'dàjiā', 'Mọi người', 'pronoun', 'pronouns', 'HSK 2'],
  ['别人', 'biérén', 'Người khác', 'pronoun', 'pronouns', 'HSK 2'],
  ['谁', 'shéi', 'Ai, người nào', 'pronoun', 'pronouns', 'HSK 1'],
  ['什么', 'shénme', 'Cái gì', 'pronoun', 'pronouns', 'HSK 1'],
  ['哪儿', 'nǎr', 'Ở đâu', 'pronoun', 'pronouns', 'HSK 1'],
  ['哪里', 'nǎlǐ', 'Ở nơi nào', 'pronoun', 'pronouns', 'HSK 1'],
  ['怎么', 'zěnme', 'Như thế nào, làm sao', 'pronoun', 'pronouns', 'HSK 1'],
  ['怎么样', 'zěnmeyàng', 'Ra sao, thế nào', 'pronoun', 'pronouns', 'HSK 1'],
  ['多少', 'duōshao', 'Bao nhiêu', 'pronoun', 'pronouns', 'HSK 1'],
  ['彼此', 'bǐcǐ', 'Lẫn nhau, đôi bên', 'pronoun', 'pronouns', 'HSK 4'],
  ['对方', 'duìfāng', 'Đối phương, bên kia', 'pronoun', 'pronouns', 'HSK 4'],

  // 3. family
  ['家', 'jiā', 'Gia đình, nhà', 'noun', 'family', 'HSK 1'],
  ['爸爸', 'bàba', 'Bố, ba', 'noun', 'family', 'HSK 1'],
  ['妈妈', 'māma', 'Mẹ, má', 'noun', 'family', 'HSK 1'],
  ['父母', 'fùmǔ', 'Cha mẹ, phụ huynh', 'noun', 'family', 'HSK 2'],
  ['哥哥', 'gēge', 'Anh trai', 'noun', 'family', 'HSK 1'],
  ['姐姐', 'jiějie', 'Chị gái', 'noun', 'family', 'HSK 1'],
  ['弟弟', 'dìdi', 'Em trai', 'noun', 'family', 'HSK 1'],
  ['妹妹', 'mèimei', 'Em gái', 'noun', 'family', 'HSK 1'],
  ['爷爷', 'yéye', 'Ông nội', 'noun', 'family', 'HSK 2'],
  ['奶奶', 'nǎinai', 'Bà nội', 'noun', 'family', 'HSK 2'],
  ['外公', 'wàigōng', 'Ông ngoại', 'noun', 'family', 'HSK 2'],
  ['外婆', 'wàipó', 'Bà ngoại', 'noun', 'family', 'HSK 2'],
  ['丈夫', 'zhàngfu', 'Chồng', 'noun', 'family', 'HSK 2'],
  ['妻子', 'qīzi', 'Vợ', 'noun', 'family', 'HSK 2'],
  ['老公', 'lǎogōng', 'Ông xã, chồng', 'noun', 'family', 'HSK 2'],
  ['老婆', 'lǎopó', 'Bà xã, vợ', 'noun', 'family', 'HSK 2'],
  ['儿子', 'érzi', 'Con trai', 'noun', 'family', 'HSK 1'],
  ['女儿', 'nǚ ér', 'Con gái', 'noun', 'family', 'HSK 1'],
  ['叔叔', 'shūshu', 'Chú', 'noun', 'family', 'HSK 2'],
  ['阿姨', 'āyí', 'Cô, dì', 'noun', 'family', 'HSK 2'],
  ['舅舅', 'jiùjiu', 'Cậu (anh/em của mẹ)', 'noun', 'family', 'HSK 3'],
  ['姑姑', 'gūgu', 'Cô (chị/em của bố)', 'noun', 'family', 'HSK 3'],
  ['亲戚', 'qīnqi', 'Họ hàng, thân thích', 'noun', 'family', 'HSK 3'],
  ['双胞胎', 'shuāngbāotāi', 'Sinh đôi, song sinh', 'noun', 'family', 'HSK 4'],

  // 4. people
  ['人', 'rén', 'Con người, người', 'noun', 'people', 'HSK 1'],
  ['朋友', 'péngyou', 'Bạn bè', 'noun', 'people', 'HSK 1'],
  ['老师', 'lǎoshī', 'Giáo viên, thầy cô', 'noun', 'people', 'HSK 1'],
  ['学生', 'xuésheng', 'Học sinh, sinh viên', 'noun', 'people', 'HSK 1'],
  ['医生', 'yīshēng', 'Bác sĩ', 'noun', 'people', 'HSK 1'],
  ['护士', 'hùshi', 'Y tá, điều dưỡng', 'noun', 'people', 'HSK 2'],
  ['司机', 'sījī', 'Tài xế, lái xe', 'noun', 'people', 'HSK 2'],
  ['警察', 'jǐngchá', 'Cảnh sát, công an', 'noun', 'people', 'HSK 3'],
  ['工程师', 'gōngchéngshī', 'Kỹ sư', 'noun', 'people', 'HSK 3'],
  ['设计师', 'shèjìshī', 'Nhà thiết kế', 'noun', 'people', 'HSK 3'],
  ['律师', 'lǜshī', 'Luật sư', 'noun', 'people', 'HSK 4'],
  ['记者', 'jìzhě', 'Nhà báo, phóng viên', 'noun', 'people', 'HSK 4'],
  ['厨师', 'chúshī', 'Đầu bếp', 'noun', 'people', 'HSK 3'],
  ['作家', 'zuòjiā', 'Nhà văn', 'noun', 'people', 'HSK 4'],
  ['导游', 'dǎoyóu', 'Hướng dẫn viên du lịch', 'noun', 'people', 'HSK 3'],
  ['邻居', 'línjū', 'Hàng xóm', 'noun', 'people', 'HSK 3'],
  ['顾客', 'gùkè', 'Khách hàng', 'noun', 'people', 'HSK 3'],
  ['嘉宾', 'jiābīn', 'Khách mời', 'noun', 'people', 'HSK 4'],
  ['专家', 'zhuānjiā', 'Chuyên gia', 'noun', 'people', 'HSK 4'],
  ['志愿者', 'zhìyuànzhě', 'Tình nguyện viên', 'noun', 'people', 'HSK 4'],

  // 5. numbers
  ['零', 'líng', 'Số không (0)', 'noun', 'numbers', 'HSK 1'],
  ['一', 'yī', 'Số một (1)', 'noun', 'numbers', 'HSK 1'],
  ['二', 'èr', 'Số hai (2)', 'noun', 'numbers', 'HSK 1'],
  ['两', 'liǎng', 'Hai (dùng trước lượng từ)', 'noun', 'numbers', 'HSK 1'],
  ['三', 'sān', 'Số ba (3)', 'noun', 'numbers', 'HSK 1'],
  ['四', 'sì', 'Số bốn (4)', 'noun', 'numbers', 'HSK 1'],
  ['五', 'wǔ', 'Số năm (5)', 'noun', 'numbers', 'HSK 1'],
  ['六', 'liù', 'Số sáu (6)', 'noun', 'numbers', 'HSK 1'],
  ['七', 'qī', 'Số bảy (7)', 'noun', 'numbers', 'HSK 1'],
  ['八', 'bā', 'Số tám (8)', 'noun', 'numbers', 'HSK 1'],
  ['九', 'jiǔ', 'Số chín (9)', 'noun', 'numbers', 'HSK 1'],
  ['十', 'shí', 'Số mười (10)', 'noun', 'numbers', 'HSK 1'],
  ['百', 'bǎi', 'Trăm (100)', 'noun', 'numbers', 'HSK 2'],
  ['千', 'qiān', 'Nghìn (1.000)', 'noun', 'numbers', 'HSK 2'],
  ['万', 'wàn', 'Vạn, mười nghìn (10.000)', 'noun', 'numbers', 'HSK 3'],
  ['百万', 'bǎiwàn', 'Một triệu (1.000.000)', 'noun', 'numbers', 'HSK 3'],
  ['亿', 'yì', 'Một trăm triệu (100.000.000)', 'noun', 'numbers', 'HSK 4'],
  ['一半', 'yíbàn', 'Một nửa (50%)', 'noun', 'numbers', 'HSK 2'],
  ['第一', 'dì yī', 'Thứ nhất, số một', 'noun', 'numbers', 'HSK 2'],
  ['百分比', 'bǎifēnbǐ', 'Tỷ lệ phần trăm (%)', 'noun', 'numbers', 'HSK 4'],

  // 6. time
  ['时间', 'shíjiān', 'Thời gian', 'noun', 'time', 'HSK 2'],
  ['现在', 'xiànzài', 'Bây giờ, hiện tại', 'noun', 'time', 'HSK 1'],
  ['小时', 'xiǎoshí', 'Tiếng đồng hồ, giờ', 'noun', 'time', 'HSK 2'],
  ['分钟', 'fēnzhōng', 'Phút', 'noun', 'time', 'HSK 1'],
  ['秒', 'miǎo', 'Giây', 'noun', 'time', 'HSK 3'],
  ['早上', 'zǎoshang', 'Buổi sáng sớm', 'noun', 'time', 'HSK 1'],
  ['上午', 'shàngwǔ', 'Buổi sáng (trước 12h)', 'noun', 'time', 'HSK 1'],
  ['中午', 'zhōngwǔ', 'Buổi trưa', 'noun', 'time', 'HSK 1'],
  ['下午', 'xiàwǔ', 'Buổi chiều', 'noun', 'time', 'HSK 1'],
  ['傍晚', 'bàngwǎn', 'Chập tối, hoàng hôn', 'noun', 'time', 'HSK 4'],
  ['晚上', 'wǎnshang', 'Buổi tối', 'noun', 'time', 'HSK 1'],
  ['半夜', 'bànyè', 'Nửa đêm', 'noun', 'time', 'HSK 3'],
  ['瞬间', 'shùnjiān', 'Khoảnh khắc, chớp mắt', 'noun', 'time', 'HSK 5'],
  ['准时', 'zhǔnshí', 'Đúng giờ', 'adjective', 'time', 'HSK 3'],

  // 7. dates
  ['今天', 'jīntiān', 'Hôm nay', 'noun', 'dates', 'HSK 1'],
  ['明天', 'míngtiān', 'Ngày mai', 'noun', 'dates', 'HSK 1'],
  ['昨天', 'zuótiān', 'Hôm qua', 'noun', 'dates', 'HSK 1'],
  ['前天', 'qiántiān', 'Hôm kia', 'noun', 'dates', 'HSK 2'],
  ['后天', 'hòutiān', 'Ngày kia', 'noun', 'dates', 'HSK 2'],
  ['星期', 'xīngqī', 'Tuần lễ, thứ', 'noun', 'dates', 'HSK 1'],
  ['周末', 'zhōumò', 'Cuối tuần', 'noun', 'dates', 'HSK 2'],
  ['月份', 'yuèfèn', 'Tháng (trong năm)', 'noun', 'dates', 'HSK 2'],
  ['今年', 'jīnnián', 'Năm nay', 'noun', 'dates', 'HSK 1'],
  ['明年', 'míngnián', 'Năm sau, sang năm', 'noun', 'dates', 'HSK 2'],
  ['去年', 'qùnián', 'Năm ngoái', 'noun', 'dates', 'HSK 2'],
  ['春天', 'chūntiān', 'Mùa xuân', 'noun', 'dates', 'HSK 2'],
  ['夏天', 'xiàtiān', 'Mùa hè', 'noun', 'dates', 'HSK 2'],
  ['秋天', 'qiūtiān', 'Mùa thu', 'noun', 'dates', 'HSK 2'],
  ['冬天', 'dōngtiān', 'Mùa đông', 'noun', 'dates', 'HSK 2'],
  ['春节', 'Chūnjié', 'Tết Nguyên Đán', 'noun', 'dates', 'HSK 3'],
  ['中秋节', 'Zhōngqiūjié', 'Tết Trung Thu', 'noun', 'dates', 'HSK 3'],

  // 8. colors
  ['颜色', 'yánsè', 'Màu sắc', 'noun', 'colors', 'HSK 2'],
  ['红色', 'hóngsè', 'Màu đỏ', 'noun', 'colors', 'HSK 2'],
  ['黄色', 'huángsè', 'Màu vàng', 'noun', 'colors', 'HSK 2'],
  ['蓝色', 'lánsè', 'Màu xanh dương', 'noun', 'colors', 'HSK 2'],
  ['绿色', 'lǜsè', 'Màu xanh lá cây', 'noun', 'colors', 'HSK 2'],
  ['白色', 'báisè', 'Màu trắng', 'noun', 'colors', 'HSK 2'],
  ['黑色', 'hēisè', 'Màu đen', 'noun', 'colors', 'HSK 2'],
  ['粉色', 'fěnsè', 'Màu hồng', 'noun', 'colors', 'HSK 3'],
  ['紫色', 'zǐsè', 'Màu tím', 'noun', 'colors', 'HSK 3'],
  ['灰色', 'huīsè', 'Màu xám', 'noun', 'colors', 'HSK 3'],
  ['棕色', 'zōngsè', 'Màu nâu', 'noun', 'colors', 'HSK 4'],
  ['金色', 'jīnsè', 'Màu vàng kim', 'noun', 'colors', 'HSK 4'],
  ['银色', 'yínsè', 'Màu bạc', 'noun', 'colors', 'HSK 4'],
  ['圆形', 'yuánxíng', 'Hình tròn', 'noun', 'colors', 'HSK 3'],
  ['方形', 'fāngxíng', 'Hình vuông', 'noun', 'colors', 'HSK 3'],

  // 9. food
  ['米饭', 'mǐfàn', 'Cơm trắng', 'noun', 'food', 'HSK 1'],
  ['面条', 'miàntiáo', 'Mì sợi', 'noun', 'food', 'HSK 2'],
  ['包子', 'bāozi', 'Bánh bao', 'noun', 'food', 'HSK 2'],
  ['饺子', 'jiǎozi', 'Há cảo, sủi cảo', 'noun', 'food', 'HSK 2'],
  ['牛肉粉', 'niúròufěn', 'Phở bò', 'noun', 'food', 'HSK 2'],
  ['春卷', 'chūnjuǎn', 'Nem rán, gỏi cuốn', 'noun', 'food', 'HSK 2'],
  ['面包', 'miànbāo', 'Bánh mì', 'noun', 'food', 'HSK 2'],
  ['鸡蛋', 'jīdàn', 'Trứng gà', 'noun', 'food', 'HSK 2'],
  ['猪肉', 'zhūròu', 'Thịt heo (lợn)', 'noun', 'food', 'HSK 2'],
  ['牛肉', 'niúròu', 'Thịt bò', 'noun', 'food', 'HSK 2'],
  ['鸡肉', 'jīròu', 'Thịt gà', 'noun', 'food', 'HSK 2'],
  ['海鲜', 'hǎixiān', 'Hải sản', 'noun', 'food', 'HSK 3'],
  ['豆腐', 'dòufu', 'Đậu phụ (đậu hũ)', 'noun', 'food', 'HSK 3'],
  ['火锅', 'huǒguō', 'Lẩu', 'noun', 'food', 'HSK 3'],
  ['烧烤', 'shāokǎo', 'Đồ nướng BBQ', 'noun', 'food', 'HSK 3'],
  ['甜点', 'tiándiǎn', 'Món tráng miệng', 'noun', 'food', 'HSK 3'],

  // 10. drinks
  ['水', 'shuǐ', 'Nước', 'noun', 'drinks', 'HSK 1'],
  ['矿泉水', 'kuàngquánshuǐ', 'Nước khoáng', 'noun', 'drinks', 'HSK 3'],
  ['茶', 'chá', 'Trà, chè', 'noun', 'drinks', 'HSK 1'],
  ['绿茶', 'lǜchá', 'Trà xanh', 'noun', 'drinks', 'HSK 2'],
  ['奶茶', 'nǎichá', 'Trà sữa', 'noun', 'drinks', 'HSK 2'],
  ['珍珠奶茶', 'zhēnzhū nǎichá', 'Trà sữa trân châu', 'noun', 'drinks', 'HSK 3'],
  ['咖啡', 'kāfēi', 'Cà phê', 'noun', 'drinks', 'HSK 2'],
  ['冰咖啡', 'bīng kāfēi', 'Cà phê đá', 'noun', 'drinks', 'HSK 2'],
  ['牛奶', 'niúnǎi', 'Sữa tươi', 'noun', 'drinks', 'HSK 2'],
  ['豆浆', 'dòujiāng', 'Sữa đậu nành', 'noun', 'drinks', 'HSK 3'],
  ['果汁', 'guǒzhī', 'Nước ép trái cây', 'noun', 'drinks', 'HSK 2'],
  ['椰子水', 'yēzishuǐ', 'Nước dừa tươi', 'noun', 'drinks', 'HSK 3'],
  ['啤酒', 'píjiǔ', 'Bia', 'noun', 'drinks', 'HSK 2'],
  ['红酒', 'hóngjiǔ', 'Rượu vang đỏ', 'noun', 'drinks', 'HSK 3'],

  // 11. restaurant
  ['餐厅', 'cāntīng', 'Nhà hàng', 'noun', 'restaurant', 'HSK 2'],
  ['菜单', 'càidān', 'Thực đơn (Menu)', 'noun', 'restaurant', 'HSK 2'],
  ['服务员', 'fúwùyuán', 'Nhân viên phục vụ', 'noun', 'restaurant', 'HSK 2'],
  ['点菜', 'diǎncài', 'Gọi món', 'verb', 'restaurant', 'HSK 2'],
  ['买单', 'mǎidān', 'Thanh toán tiền ăn', 'verb', 'restaurant', 'HSK 3'],
  ['打包', 'dǎbāo', 'Đóng gói mang về', 'verb', 'restaurant', 'HSK 3'],
  ['外卖', 'wàimài', 'Đồ ăn giao tận nơi', 'noun', 'restaurant', 'HSK 3'],
  ['筷子', 'kuàizi', 'Đôi đũa', 'noun', 'restaurant', 'HSK 3'],
  ['勺子', 'sháozi', 'Cái thìa (muỗng)', 'noun', 'restaurant', 'HSK 3'],
  ['餐巾纸', 'cānjīnzhǐ', 'Khăn giấy ăn', 'noun', 'restaurant', 'HSK 3'],
  ['招牌菜', 'zhāopáicài', 'Món đặc sản của quán', 'noun', 'restaurant', 'HSK 4'],
  ['微辣', 'wēilà', 'Cay ít (cay nhẹ)', 'adjective', 'restaurant', 'HSK 3'],
  ['不加香菜', 'bù jiā xiāngcài', 'Không cho rau mùi (ngò)', 'phrase', 'restaurant', 'HSK 3'],
  ['素食', 'sùshí', 'Đồ chay', 'noun', 'restaurant', 'HSK 4'],

  // 12. shopping
  ['买', 'mǎi', 'Mua', 'verb', 'shopping', 'HSK 1'],
  ['卖', 'mài', 'Bán', 'verb', 'shopping', 'HSK 2'],
  ['便宜', 'piányi', 'Rẻ', 'adjective', 'shopping', 'HSK 2'],
  ['贵', 'guì', 'Đắt', 'adjective', 'shopping', 'HSK 2'],
  ['打折', 'dǎzhé', 'Giảm giá, chiết khấu', 'verb', 'shopping', 'HSK 3'],
  ['包邮', 'bāoyóu', 'Miễn phí vận chuyển (Freeship)', 'verb', 'shopping', 'HSK 3'],
  ['优惠券', 'yōuhuìquàn', 'Mã giảm giá (Voucher)', 'noun', 'shopping', 'HSK 4'],
  ['收据', 'shōujù', 'Hóa đơn, biên lai', 'noun', 'shopping', 'HSK 4'],
  ['退货', 'tuìhuò', 'Trả hàng hoàn tiền', 'verb', 'shopping', 'HSK 4'],
  ['换货', 'huànhuò', 'Đổi hàng', 'verb', 'shopping', 'HSK 4'],
  ['付款', 'fùkuǎn', 'Thanh toán', 'verb', 'shopping', 'HSK 3'],
  ['扫码支付', 'sǎomǎ zhīfù', 'Quét mã QR thanh toán', 'phrase', 'shopping', 'HSK 3'],
  ['现金', 'xiànjīn', 'Tiền mặt', 'noun', 'shopping', 'HSK 3'],
  ['找零', 'zhǎolíng', 'Trả lại tiền thừa', 'verb', 'shopping', 'HSK 3'],

  // 13. clothing
  ['衣服', 'yīfu', 'Quần áo', 'noun', 'clothing', 'HSK 1'],
  ['衬衫', 'chènshān', 'Áo sơ mi', 'noun', 'clothing', 'HSK 3'],
  ['T恤', 'T-xù', 'Áo phông (áo thun)', 'noun', 'clothing', 'HSK 2'],
  ['外套', 'wàitào', 'Áo khoác ngoài', 'noun', 'clothing', 'HSK 3'],
  ['毛衣', 'máoyī', 'Áo len', 'noun', 'clothing', 'HSK 3'],
  ['裤子', 'kùzi', 'Quần dài', 'noun', 'clothing', 'HSK 2'],
  ['牛仔裤', 'niúzǎikù', 'Quần bò (quần jeans)', 'noun', 'clothing', 'HSK 3'],
  ['裙子', 'qúnzi', 'Chân váy, đầm', 'noun', 'clothing', 'HSK 2'],
  ['连衣裙', 'liányīqún', 'Váy liền thân (đầm)', 'noun', 'clothing', 'HSK 3'],
  ['奥黛', 'àodài', 'Áo dài Việt Nam', 'noun', 'clothing', 'HSK 3'],
  ['鞋子', 'xiézi', 'Giày dép', 'noun', 'clothing', 'HSK 2'],
  ['运动鞋', 'yùndòngxié', 'Giày thể thao', 'noun', 'clothing', 'HSK 3'],
  ['眼镜', 'yǎnjìng', 'Mắt kính', 'noun', 'clothing', 'HSK 3'],
  ['手表', 'shǒubiǎo', 'Đồng hồ đeo tay', 'noun', 'clothing', 'HSK 2'],

  // 14. housing
  ['房子', 'fángzi', 'Ngôi nhà, căn hộ', 'noun', 'housing', 'HSK 2'],
  ['公寓', 'gōngyù', 'Căn hộ chung cư', 'noun', 'housing', 'HSK 3'],
  ['房间', 'fángjiān', 'Căn phòng', 'noun', 'housing', 'HSK 2'],
  ['客厅', 'kètīng', 'Phòng khách', 'noun', 'housing', 'HSK 3'],
  ['卧室', 'wòshì', 'Phòng ngủ', 'noun', 'housing', 'HSK 3'],
  ['厨房', 'chúfáng', 'Phòng bếp', 'noun', 'housing', 'HSK 3'],
  ['卫生间', 'wèishēngjiān', 'Phòng vệ sinh, nhà tắm', 'noun', 'housing', 'HSK 2'],
  ['阳台', 'yángtái', 'Ban công', 'noun', 'housing', 'HSK 3'],
  ['租房', 'zūfáng', 'Thuê nhà', 'verb', 'housing', 'HSK 3'],
  ['房东', 'fángdōng', 'Chủ nhà cho thuê', 'noun', 'housing', 'HSK 3'],
  ['房租', 'fángzū', 'Tiền thuê nhà', 'noun', 'housing', 'HSK 3'],
  ['押金', 'yājīn', 'Tiền đặt cọc', 'noun', 'housing', 'HSK 4'],
  ['搬家', 'bānjiā', 'Chuyển nhà', 'verb', 'housing', 'HSK 3'],
  ['物业', 'wùyè', 'Ban quản lý tòa nhà', 'noun', 'housing', 'HSK 4'],

  // 15. household
  ['桌子', 'zhuōzi', 'Cái bàn', 'noun', 'household', 'HSK 1'],
  ['椅子', 'yǐzi', 'Cái ghế', 'noun', 'household', 'HSK 1'],
  ['沙发', 'shāfā', 'Ghế sofa', 'noun', 'household', 'HSK 3'],
  ['床', 'chuáng', 'Cái giường', 'noun', 'household', 'HSK 2'],
  ['衣柜', 'yīguì', 'Tủ quần áo', 'noun', 'household', 'HSK 3'],
  ['空调', 'kōngtiáo', 'Máy điều hòa', 'noun', 'household', 'HSK 3'],
  ['冰箱', 'bīngxiāng', 'Tủ lạnh', 'noun', 'household', 'HSK 3'],
  ['洗衣机', 'xǐyījī', 'Máy giặt', 'noun', 'household', 'HSK 3'],
  ['风扇', 'fēngshàn', 'Quạt điện', 'noun', 'household', 'HSK 3'],
  ['镜子', 'jìngzi', 'Cái gương', 'noun', 'household', 'HSK 3'],
  ['牙刷', 'yáshuā', 'Bàn chải đánh răng', 'noun', 'household', 'HSK 3'],
  ['牙膏', 'yágāo', 'Kem đánh răng', 'noun', 'household', 'HSK 3'],
  ['毛巾', 'máojīn', 'Khăn mặt, khăn tắm', 'noun', 'household', 'HSK 3'],
  ['钥匙', 'yàoshi', 'Chìa khóa', 'noun', 'household', 'HSK 3'],

  // 16. school
  ['学校', 'xuéxiào', 'Trường học', 'noun', 'school', 'HSK 1'],
  ['大学', 'dàxué', 'Trường đại học', 'noun', 'school', 'HSK 2'],
  ['教室', 'jiàoshì', 'Lớp học, phòng học', 'noun', 'school', 'HSK 2'],
  ['图书馆', 'túshūguǎn', 'Thư viện', 'noun', 'school', 'HSK 3'],
  ['考试', 'kǎoshì', 'Thi cử, bài kiểm tra', 'noun', 'school', 'HSK 2'],
  ['作业', 'zuòyè', 'Bài tập về nhà', 'noun', 'school', 'HSK 3'],
  ['成绩', 'chéngjì', 'Thành tích, điểm số', 'noun', 'school', 'HSK 3'],
  ['奖学金', 'jiǎngxuéjīn', 'Học bổng', 'noun', 'school', 'HSK 4'],
  ['留学', 'liúxué', 'Du học', 'verb', 'school', 'HSK 3'],
  ['毕业', 'bìyè', 'Tốt nghiệp', 'verb', 'school', 'HSK 3'],
  ['专业', 'zhuānyè', 'Chuyên ngành', 'noun', 'school', 'HSK 4'],
  ['字典', 'zìdiǎn', 'Từ điển', 'noun', 'school', 'HSK 3'],

  // 17. work
  ['工作', 'gōngzuò', 'Công việc, làm việc', 'noun', 'work', 'HSK 1'],
  ['上班', 'shàngbān', 'Đi làm', 'verb', 'work', 'HSK 2'],
  ['下班', 'xiàbān', 'Tan làm', 'verb', 'work', 'HSK 2'],
  ['加班', 'jiābān', 'Tăng ca, làm thêm giờ', 'verb', 'work', 'HSK 4'],
  ['出差', 'chūchāi', 'Đi công tác', 'verb', 'work', 'HSK 4'],
  ['同事', 'tóngshì', 'Đồng nghiệp', 'noun', 'work', 'HSK 3'],
  ['老板', 'lǎobǎn', 'Ông chủ, sếp', 'noun', 'work', 'HSK 3'],
  ['经理', 'jīnglǐ', 'Giám đốc, quản lý', 'noun', 'work', 'HSK 3'],
  ['工资', 'gōngzī', 'Tiền lương', 'noun', 'work', 'HSK 4'],
  ['奖金', 'jiǎngjīn', 'Tiền thưởng', 'noun', 'work', 'HSK 4'],
  ['请假', 'qǐngjià', 'Xin nghỉ phép', 'verb', 'work', 'HSK 3'],
  ['辞职', 'cízhí', 'Từ chức, nghỉ việc', 'verb', 'work', 'HSK 5'],

  // 18. office
  ['办公室', 'bàngōngshì', 'Văn phòng làm việc', 'noun', 'office', 'HSK 2'],
  ['会议', 'huìyì', 'Cuộc họp, hội nghị', 'noun', 'office', 'HSK 3'],
  ['文件', 'wénjiàn', 'Tài liệu, văn kiện', 'noun', 'office', 'HSK 3'],
  ['合同', 'hétong', 'Hợp đồng', 'noun', 'office', 'HSK 4'],
  ['签字', 'qiānzì', 'Ký tên', 'verb', 'office', 'HSK 4'],
  ['盖章', 'gàizhāng', 'Đóng dấu mộc', 'verb', 'office', 'HSK 5'],
  ['打印机', 'dǎyìnjī', 'Máy in', 'noun', 'office', 'HSK 4'],
  ['复印', 'fùyìn', 'Photocopy, sao chụp', 'verb', 'office', 'HSK 4'],
  ['名片', 'míngpiàn', 'Danh thiếp (Name card)', 'noun', 'office', 'HSK 4'],
  ['报告', 'bàogào', 'Báo cáo', 'noun', 'office', 'HSK 4'],
  ['日程表', 'rìchéngbiǎo', 'Lịch trình làm việc', 'noun', 'office', 'HSK 4'],
  ['归档', 'guīdng', 'Lưu trữ hồ sơ', 'verb', 'office', 'HSK 5'],

  // 19. technology
  ['电脑', 'diànnǎo', 'Máy vi tính', 'noun', 'technology', 'HSK 1'],
  ['笔记本电脑', 'bǐjìběn diànnǎo', 'Máy tính xách tay (Laptop)', 'noun', 'technology', 'HSK 3'],
  ['平板电脑', 'píngbǎn diànnǎo', 'Máy tính bảng (Tablet)', 'noun', 'technology', 'HSK 4'],
  ['键盘', 'jiànpán', 'Bàn phím', 'noun', 'technology', 'HSK 4'],
  ['鼠标', 'shǔbiāo', 'Chuột máy tính', 'noun', 'technology', 'HSK 4'],
  ['屏幕', 'píngmù', 'Màn hình', 'noun', 'technology', 'HSK 4'],
  ['耳机', 'ěrjī', 'Tai nghe', 'noun', 'technology', 'HSK 3'],
  ['充电器', 'chōngdiànqì', 'Cục sạc, bộ sạc', 'noun', 'technology', 'HSK 3'],
  ['充电宝', 'chōngdiànbǎo', 'Sạc dự phòng', 'noun', 'technology', 'HSK 3'],
  ['芯片', 'xīnpiàn', 'Vi mạch, con chip', 'noun', 'technology', 'HSK 5'],
  ['硬件', 'yìngjiàn', 'Phần cứng', 'noun', 'technology', 'HSK 5'],
  ['软件', 'ruǎnjiàn', 'Phần mềm', 'noun', 'technology', 'HSK 4'],

  // 20. internet
  ['互联网', 'hùliánwǎng', 'Mạng Internet', 'noun', 'internet', 'HSK 4'],
  ['网站', 'wǎngzhàn', 'Trang web (Website)', 'noun', 'internet', 'HSK 4'],
  ['网页', 'wǎngyè', 'Trang mạng', 'noun', 'internet', 'HSK 4'],
  ['无线网', 'wúxiànwǎng', 'Mạng không dây (Wi-Fi)', 'noun', 'internet', 'HSK 3'],
  ['密码', 'mìmǎ', 'Mật khẩu', 'noun', 'internet', 'HSK 4'],
  ['账号', 'zhànghào', 'Tài khoản', 'noun', 'internet', 'HSK 4'],
  ['登录', 'dēnglù', 'Đăng nhập', 'verb', 'internet', 'HSK 4'],
  ['注册', 'zhùcè', 'Đăng ký tài khoản', 'verb', 'internet', 'HSK 4'],
  ['下载', 'xiàzǎi', 'Tải xuống (Download)', 'verb', 'internet', 'HSK 4'],
  ['上传', 'shàngchuán', 'Tải lên (Upload)', 'verb', 'internet', 'HSK 4'],
  ['链接', 'liànjiē', 'Đường dẫn (Link)', 'noun', 'internet', 'HSK 4'],
  ['浏览器', 'liúlǎnqì', 'Trình duyệt web', 'noun', 'internet', 'HSK 5'],

  // 21. phone
  ['手机', 'shǒujī', 'Điện thoại di động', 'noun', 'phone', 'HSK 2'],
  ['打电话', 'dǎ diànhuà', 'Gọi điện thoại', 'verb', 'phone', 'HSK 1'],
  ['接电话', 'jiē diànhuà', 'Nghe máy, nhận cuộc gọi', 'verb', 'phone', 'HSK 2'],
  ['发短信', 'fā duǎnxìn', 'Gửi tin nhắn SMS', 'verb', 'phone', 'HSK 3'],
  ['通话', 'tōnghuà', 'Đàm thoại, cuộc gọi', 'verb', 'phone', 'HSK 4'],
  ['信号', 'xìnhào', 'Tín hiệu, sóng điện thoại', 'noun', 'phone', 'HSK 4'],
  ['流量', 'liúliàng', 'Dung lượng dữ liệu 4G/5G', 'noun', 'phone', 'HSK 4'],
  ['话费', 'huàfèi', 'Cước phí điện thoại', 'noun', 'phone', 'HSK 4'],
  ['关机', 'guānjī', 'Tắt nguồn điện thoại', 'verb', 'phone', 'HSK 3'],
  ['静音', 'jìngyīn', 'Chế độ im lặng', 'verb', 'phone', 'HSK 4'],
  ['截图', 'jiétú', 'Chụp màn hình', 'verb', 'phone', 'HSK 4'],
  ['语音通话', 'yǔyīn tōnghuà', 'Cuộc gọi thoại', 'noun', 'phone', 'HSK 4'],

  // 22. social_media
  ['社交媒体', 'shèjiāo méitǐ', 'Mạng xã hội', 'noun', 'social_media', 'HSK 4'],
  ['直播', 'zhíbō', 'Phát trực tiếp (Livestream)', 'verb', 'social_media', 'HSK 4'],
  ['主播', 'zhǔbō', 'Người dẫn livestream (Streamer)', 'noun', 'social_media', 'HSK 4'],
  ['短视频', 'duǎnshìpín', 'Video ngắn (Reels/TikTok)', 'noun', 'social_media', 'HSK 4'],
  ['点赞', 'diǎnzàn', 'Thả tim, bấm thích (Like)', 'verb', 'social_media', 'HSK 4'],
  ['评论', 'pínglùn', 'Bình luận (Comment)', 'noun', 'social_media', 'HSK 4'],
  ['转发', 'zhuǎnfā', 'Chia sẻ lại (Share)', 'verb', 'social_media', 'HSK 4'],
  ['关注', 'guānzhù', 'Theo dõi (Follow)', 'verb', 'social_media', 'HSK 4'],
  ['粉丝', 'fěnsī', 'Người hâm mộ (Fan/Follower)', 'noun', 'social_media', 'HSK 4'],
  ['网红', 'wǎnghóng', 'Người nổi tiếng trên mạng (KOL)', 'noun', 'social_media', 'HSK 4'],
  ['朋友圈', 'péngyouquān', 'Bảng tin bạn bè (Moments)', 'noun', 'social_media', 'HSK 4'],
  ['表情包', 'biǎoqíngbāo', 'Bộ nhãn dán (Sticker/Meme)', 'noun', 'social_media', 'HSK 4'],

  // 23. travel
  ['旅游', 'lǚyóu', 'Du lịch', 'verb', 'travel', 'HSK 2'],
  ['景点', 'jǐngdiǎn', 'Điểm tham quan, danh lam', 'noun', 'travel', 'HSK 3'],
  ['门票', 'ménpiào', 'Vé vào cổng', 'noun', 'travel', 'HSK 3'],
  ['纪念品', 'jìniànpǐn', 'Quà lưu niệm', 'noun', 'travel', 'HSK 4'],
  ['拍照', 'pāizhào', 'Chụp ảnh', 'verb', 'travel', 'HSK 3'],
  ['风景', 'fēngjǐng', 'Phong cảnh', 'noun', 'travel', 'HSK 3'],
  ['行程', 'xíngchéng', 'Lịch trình chuyến đi', 'noun', 'travel', 'HSK 4'],
  ['自由行', 'zìyóuxíng', 'Du lịch tự túc', 'noun', 'travel', 'HSK 4'],
  ['跟团游', 'gēntuányóu', 'Du lịch theo tour', 'noun', 'travel', 'HSK 4'],
  ['度假', 'dùjià', 'Nghỉ dưỡng', 'verb', 'travel', 'HSK 4'],
  ['名胜古迹', 'míngshèng gǔjì', 'Danh lam thắng cảnh cổ', 'noun', 'travel', 'HSK 5'],
  ['打卡', 'dǎkǎ', 'Check-in địa điểm', 'verb', 'travel', 'HSK 4'],

  // 24. hotel
  ['酒店', 'jiǔdiàn', 'Khách sạn', 'noun', 'hotel', 'HSK 2'],
  ['宾馆', 'bīnguǎn', 'Nhà nghỉ, khách sạn', 'noun', 'hotel', 'HSK 2'],
  ['民宿', 'mínsù', 'Homestay', 'noun', 'hotel', 'HSK 4'],
  ['预订', 'yùdìng', 'Đặt trước (Booking)', 'verb', 'hotel', 'HSK 4'],
  ['入住', 'rùzhù', 'Nhận phòng (Check-in)', 'verb', 'hotel', 'HSK 4'],
  ['退房', 'tuìfáng', 'Trả phòng (Check-out)', 'verb', 'hotel', 'HSK 4'],
  ['前台', 'qiántái', 'Quầy lễ tân', 'noun', 'hotel', 'HSK 3'],
  ['房卡', 'fángkǎ', 'Thẻ phòng khách sạn', 'noun', 'hotel', 'HSK 3'],
  ['单人间', 'dānrénjiān', 'Phòng đơn', 'noun', 'hotel', 'HSK 3'],
  ['双人间', 'shuāngrénjiān', 'Phòng đôi', 'noun', 'hotel', 'HSK 3'],
  ['含早', 'hánzǎo', 'Bao gồm bữa sáng', 'phrase', 'hotel', 'HSK 4'],
  ['行李寄存', 'xíngli jìcún', 'Gửi hành lý tại lễ tân', 'phrase', 'hotel', 'HSK 4'],

  // 25. airport
  ['机场', 'jīchǎng', 'Sân bay', 'noun', 'airport', 'HSK 2'],
  ['飞机', 'fēijī', 'Máy bay', 'noun', 'airport', 'HSK 1'],
  ['机票', 'jīpiào', 'Vé máy bay', 'noun', 'airport', 'HSK 2'],
  ['护照', 'hùzhào', 'Hộ chiếu (Passport)', 'noun', 'airport', 'HSK 3'],
  ['签证', 'qiānzhèng', 'Thị thực (Visa)', 'noun', 'airport', 'HSK 4'],
  ['登机牌', 'dēngjīpái', 'Thẻ lên máy bay (Boarding pass)', 'noun', 'airport', 'HSK 4'],
  ['托运', 'tuōyùn', 'Ký gửi hành lý', 'verb', 'airport', 'HSK 4'],
  ['安检', 'ānjiǎn', 'Kiểm tra an ninh', 'noun', 'airport', 'HSK 4'],
  ['海关', 'hǎiguān', 'Hải quan', 'noun', 'airport', 'HSK 4'],
  ['航班', 'hángbān', 'Chuyến bay', 'noun', 'airport', 'HSK 4'],
  ['延误', 'yánwù', 'Hoãn chuyến (Delay)', 'verb', 'airport', 'HSK 5'],
  ['免税店', 'miǎnshuìdiàn', 'Cửa hàng miễn thuế', 'noun', 'airport', 'HSK 4'],

  // 26. transport
  ['出租车', 'chūzūchē', 'Xe taxi', 'noun', 'transport', 'HSK 1'],
  ['网约车', 'wǎngyuēchē', 'Xe công nghệ (Grab/Didi)', 'noun', 'transport', 'HSK 4'],
  ['公交车', 'gōngjiāochē', 'Xe buýt', 'noun', 'transport', 'HSK 2'],
  ['地铁', 'dìtiě', 'Tàu điện ngầm (Metro)', 'noun', 'transport', 'HSK 3'],
  ['高铁', 'gāotiě', 'Tàu cao tốc', 'noun', 'transport', 'HSK 3'],
  ['火车', 'huǒchē', 'Tàu hỏa', 'noun', 'transport', 'HSK 2'],
  ['摩托车', 'mótuōchē', 'Xe máy', 'noun', 'transport', 'HSK 3'],
  ['自行车', 'zìxíngchē', 'Xe đạp', 'noun', 'transport', 'HSK 2'],
  ['堵车', 'dǔchē', 'Tắc đường, kẹt xe', 'verb', 'transport', 'HSK 4'],
  ['红绿灯', 'hónglǜdēng', 'Đèn giao thông', 'noun', 'transport', 'HSK 3'],
  ['安全帽', 'ānquánmào', 'Mũ bảo hiểm', 'noun', 'transport', 'HSK 3'],
  ['导航', 'dǎoháng', 'Bản đồ dẫn đường (GPS)', 'noun', 'transport', 'HSK 4'],

  // 27. city
  ['城市', 'chéngshì', 'Thành phố', 'noun', 'city', 'HSK 3'],
  ['首都', 'shǒudū', 'Thủ đô', 'noun', 'city', 'HSK 4'],
  ['街道', 'jiēdào', 'Đường phố', 'noun', 'city', 'HSK 3'],
  ['广场', 'guǎngchǎng', 'Quảng trường', 'noun', 'city', 'HSK 4'],
  ['公园', 'gōngyuán', 'Công viên', 'noun', 'city', 'HSK 2'],
  ['超市', 'chāoshì', 'Siêu thị', 'noun', 'city', 'HSK 3'],
  ['便利店', 'biànlìdiàn', 'Cửa hàng tiện lợi', 'noun', 'city', 'HSK 3'],
  ['商场', 'shāngchǎng', 'Trung tâm thương mại', 'noun', 'city', 'HSK 3'],
  ['夜市', 'yèshì', 'Chợ đêm', 'noun', 'city', 'HSK 3'],
  ['步行街', 'bùxíngjiē', 'Phố đi bộ', 'noun', 'city', 'HSK 4'],
  ['博物馆', 'bówùguǎn', 'Viện bảo tàng', 'noun', 'city', 'HSK 4'],
  ['地标', 'dìbiāo', 'Biểu tượng thành phố (Landmark)', 'noun', 'city', 'HSK 5'],

  // 28. places
  ['前面', 'qiánmiàn', 'Phía trước', 'noun', 'places', 'HSK 1'],
  ['后面', 'hòumiàn', 'Phía sau', 'noun', 'places', 'HSK 1'],
  ['左边', 'zuǒbiān', 'Bên trái', 'noun', 'places', 'HSK 2'],
  ['右边', 'yòubiān', 'Bên phải', 'noun', 'places', 'HSK 2'],
  ['旁边', 'pángbiān', 'Bên cạnh', 'noun', 'places', 'HSK 2'],
  ['对面', 'duìmiàn', 'Đối diện', 'noun', 'places', 'HSK 3'],
  ['中间', 'zhōngjiān', 'Ở giữa', 'noun', 'places', 'HSK 3'],
  ['附近', 'fùjìn', 'Gần đây, lân cận', 'noun', 'places', 'HSK 3'],
  ['里面', 'lǐmiàn', 'Bên trong', 'noun', 'places', 'HSK 2'],
  ['外面', 'wàimiàn', 'Bên ngoài', 'noun', 'places', 'HSK 2'],
  ['楼上', 'lóushàng', 'Trên lầu', 'noun', 'places', 'HSK 2'],
  ['楼下', 'lóuxià', 'Dưới lầu', 'noun', 'places', 'HSK 2'],

  // 29. health
  ['医院', 'yīyuàn', 'Bệnh viện', 'noun', 'health', 'HSK 1'],
  ['药店', 'yàodiàn', 'Hiệu thuốc, nhà thuốc', 'noun', 'health', 'HSK 3'],
  ['生病', 'shēngbìng', 'Bị ốm, mắc bệnh', 'verb', 'health', 'HSK 2'],
  ['感冒', 'gǎnmào', 'Cảm cúm', 'verb', 'health', 'HSK 3'],
  ['发烧', 'fāshāo', 'Bị sốt', 'verb', 'health', 'HSK 3'],
  ['咳嗽', 'késou', 'Ho', 'verb', 'health', 'HSK 4'],
  ['过敏', 'guòmǐn', 'Dị ứng', 'verb', 'health', 'HSK 5'],
  ['吃药', 'chīyào', 'Uống thuốc', 'verb', 'health', 'HSK 2'],
  ['体检', 'tǐjiǎn', 'Khám sức khỏe tổng quát', 'noun', 'health', 'HSK 4'],
  ['保险', 'bǎoxiǎn', 'Bảo hiểm', 'noun', 'health', 'HSK 4'],
  ['挂号', 'guàhào', 'Lấy số khám bệnh', 'verb', 'health', 'HSK 4'],
  ['处方', 'chǔfāng', 'Đơn thuốc', 'noun', 'health', 'HSK 5'],

  // 30. body
  ['身体', 'shēntǐ', 'Cơ thể, sức khỏe', 'noun', 'body', 'HSK 2'],
  ['头', 'tóu', 'Cái đầu', 'noun', 'body', 'HSK 2'],
  ['头发', 'tóufa', 'Mái tóc', 'noun', 'body', 'HSK 3'],
  ['眼睛', 'yǎnjing', 'Đôi mắt', 'noun', 'body', 'HSK 2'],
  ['鼻子', 'bízi', 'Cái mũi', 'noun', 'body', 'HSK 3'],
  ['嘴巴', 'zuǐba', 'Cái miệng', 'noun', 'body', 'HSK 3'],
  ['耳朵', 'ěrduo', 'Đôi tai', 'noun', 'body', 'HSK 3'],
  ['手', 'shǒu', 'Bàn tay', 'noun', 'body', 'HSK 2'],
  ['脚', 'jiǎo', 'Bàn chân', 'noun', 'body', 'HSK 3'],
  ['肚子', 'dùzi', 'Cái bụng', 'noun', 'body', 'HSK 3'],
  ['心脏', 'xīnzàng', 'Trái tim, quả tim', 'noun', 'body', 'HSK 4'],
  ['皮肤', 'pífū', 'Làn da', 'noun', 'body', 'HSK 4'],

  // 31. emotions
  ['高兴', 'gāoxìng', 'Vui vẻ, phấn khởi', 'adjective', 'emotions', 'HSK 1'],
  ['开心', 'kāixīn', 'Vui sướng, hạnh phúc', 'adjective', 'emotions', 'HSK 2'],
  ['幸福', 'xìngfú', 'Hạnh phúc viên mãn', 'adjective', 'emotions', 'HSK 4'],
  ['难过', 'nánguò', 'Buồn bã', 'adjective', 'emotions', 'HSK 3'],
  ['伤心', 'shāngxīn', 'Đau lòng', 'adjective', 'emotions', 'HSK 4'],
  ['生气', 'shēngqì', 'Tức giận', 'verb', 'emotions', 'HSK 3'],
  ['担心', 'dānxīn', 'Lo lắng', 'verb', 'emotions', 'HSK 3'],
  ['害怕', 'hàipà', 'Sợ hãi', 'verb', 'emotions', 'HSK 3'],
  ['紧张', 'jǐnzhāng', 'Căng thẳng, hồi hộp', 'adjective', 'emotions', 'HSK 4'],
  ['感动', 'gǎndòng', 'Cảm động', 'adjective', 'emotions', 'HSK 4'],
  ['满意', 'mǎnyì', 'Hài lòng', 'adjective', 'emotions', 'HSK 3'],
  ['失望', 'shīwàng', 'Thất vọng', 'adjective', 'emotions', 'HSK 4'],

  // 32. personality
  ['性格', 'xìnggé', 'Tính cách', 'noun', 'personality', 'HSK 4'],
  ['热情', 'rèqíng', 'Nhiệt tình, nồng hậu', 'adjective', 'personality', 'HSK 3'],
  ['温柔', 'wēnróu', 'Dịu dàng', 'adjective', 'personality', 'HSK 5'],
  ['聪明', 'cōngming', 'Thông minh', 'adjective', 'personality', 'HSK 3'],
  ['努力', 'nǔlì', 'Chăm chỉ, nỗ lực', 'adjective', 'personality', 'HSK 3'],
  ['认真', 'rènzhēn', 'Nghiêm túc, cẩn thận', 'adjective', 'personality', 'HSK 3'],
  ['幽默', 'yōumò', 'Hài hước', 'adjective', 'personality', 'HSK 4'],
  ['诚实', 'chéngshí', 'Trung thực, thật thà', 'adjective', 'personality', 'HSK 4'],
  ['善良', 'shànliáng', 'Lương thiện, tốt bụng', 'adjective', 'personality', 'HSK 5'],
  ['自信', 'zìxìn', 'Tự tin', 'adjective', 'personality', 'HSK 4'],
  ['独立', 'dúlì', 'Độc lập, tự lập', 'adjective', 'personality', 'HSK 5'],
  ['耐心', 'nàixīn', 'Kiên nhẫn', 'adjective', 'personality', 'HSK 4'],

  // 33. nature
  ['大自然', 'dàzìrán', 'Thiên nhiên', 'noun', 'nature', 'HSK 4'],
  ['大海', 'dàhǎi', 'Biển cả, đại dương', 'noun', 'nature', 'HSK 3'],
  ['沙滩', 'shātān', 'Bãi biển, bãi cát', 'noun', 'nature', 'HSK 4'],
  ['森林', 'sēnlín', 'Rừng rậm', 'noun', 'nature', 'HSK 4'],
  ['高山', 'gāoshān', 'Núi cao', 'noun', 'nature', 'HSK 3'],
  ['河流', 'héliú', 'Sông ngòi', 'noun', 'nature', 'HSK 4'],
  ['空气', 'kōngqì', 'Không khí', 'noun', 'nature', 'HSK 4'],
  ['太阳', 'tàiyáng', 'Mặt trời', 'noun', 'nature', 'HSK 3'],
  ['月亮', 'yuèliang', 'Mặt trăng', 'noun', 'nature', 'HSK 3'],
  ['星星', 'xīngxing', 'Ngôi sao', 'noun', 'nature', 'HSK 3'],
  ['环保', 'huánbǎo', 'Bảo vệ môi trường', 'noun', 'nature', 'HSK 4'],
  ['生态', 'shēngtài', 'Sinh thái', 'noun', 'nature', 'HSK 5'],

  // 34. weather
  ['天气', 'tiānqì', 'Thời tiết', 'noun', 'weather', 'HSK 1'],
  ['晴天', 'qíngtiān', 'Trời nắng đẹp', 'noun', 'weather', 'HSK 2'],
  ['阴天', 'yīntiān', 'Trời âm u, nhiều mây', 'noun', 'weather', 'HSK 2'],
  ['下雨', 'xiàyǔ', 'Trời mưa', 'verb', 'weather', 'HSK 1'],
  ['下雪', 'xiàxuě', 'Tuyết rơi', 'verb', 'weather', 'HSK 2'],
  ['刮风', 'guāfēng', 'Gió thổi', 'verb', 'weather', 'HSK 3'],
  ['台风', 'táifēng', 'Bão nhiệt đới', 'noun', 'weather', 'HSK 4'],
  ['温度', 'wēndù', 'Nhiệt độ', 'noun', 'weather', 'HSK 4'],
  ['潮湿', 'cháoshī', 'Ẩm ướt, nồm ẩm', 'adjective', 'weather', 'HSK 5'],
  ['干燥', 'gānzào', 'Khô hanh', 'adjective', 'weather', 'HSK 5'],
  ['凉快', 'liángkuai', 'Mát mẻ', 'adjective', 'weather', 'HSK 4'],
  ['暖和', 'nuǎnhuo', 'Ấm áp', 'adjective', 'weather', 'HSK 4'],

  // 35. animals
  ['动物', 'dòngwù', 'Động vật', 'noun', 'animals', 'HSK 3'],
  ['猫', 'māo', 'Con mèo', 'noun', 'animals', 'HSK 1'],
  ['狗', 'gǒu', 'Con chó', 'noun', 'animals', 'HSK 1'],
  ['熊猫', 'xióngmāo', 'Gấu trúc', 'noun', 'animals', 'HSK 3'],
  ['水牛', 'shuǐniú', 'Con trâu', 'noun', 'animals', 'HSK 3'],
  ['大象', 'dàxiàng', 'Con voi', 'noun', 'animals', 'HSK 3'],
  ['老虎', 'lǎohǔ', 'Con hổ', 'noun', 'animals', 'HSK 4'],
  ['兔子', 'tùzi', 'Con thỏ', 'noun', 'animals', 'HSK 3'],
  ['鸟', 'niǎo', 'Con chim', 'noun', 'animals', 'HSK 3'],
  ['鱼', 'yú', 'Con cá', 'noun', 'animals', 'HSK 2'],
  ['蝴蝶', 'húdié', 'Con bướm', 'noun', 'animals', 'HSK 4'],
  ['宠物', 'chǒngwù', 'Thú cưng', 'noun', 'animals', 'HSK 4'],

  // 36. plants
  ['水果', 'shuǐguǒ', 'Trái cây, hoa quả', 'noun', 'plants', 'HSK 1'],
  ['苹果', 'píngguǒ', 'Quả táo', 'noun', 'plants', 'HSK 1'],
  ['西瓜', 'xīguā', 'Quả dưa hấu', 'noun', 'plants', 'HSK 2'],
  ['香蕉', 'xiāngjiāo', 'Quả chuối', 'noun', 'plants', 'HSK 3'],
  ['芒果', 'mángguǒ', 'Quả xoài', 'noun', 'plants', 'HSK 3'],
  ['榴莲', 'liúlián', 'Quả sầu riêng', 'noun', 'plants', 'HSK 3'],
  ['火龙果', 'huǒlóngguǒ', 'Quả thanh long', 'noun', 'plants', 'HSK 3'],
  ['菠萝蜜', 'bōluómì', 'Quả mít', 'noun', 'plants', 'HSK 4'],
  ['荷花', 'héhuā', 'Hoa sen', 'noun', 'plants', 'HSK 4'],
  ['竹子', 'zhúzi', 'Cây tre, cây trúc', 'noun', 'plants', 'HSK 4'],
  ['玫瑰', 'méigui', 'Hoa hồng', 'noun', 'plants', 'HSK 4'],
  ['蔬菜', 'shūcài', 'Rau củ', 'noun', 'plants', 'HSK 3'],

  // 37. sports
  ['运动', 'yùndòng', 'Thể thao, vận động', 'noun', 'sports', 'HSK 2'],
  ['足球', 'zúqiú', 'Bóng đá', 'noun', 'sports', 'HSK 2'],
  ['篮球', 'lánqiú', 'Bóng rổ', 'noun', 'sports', 'HSK 2'],
  ['羽毛球', 'yǔmáoqiú', 'Cầu lông', 'noun', 'sports', 'HSK 3'],
  ['乒乓球', 'pīngpāngqiú', 'Bóng bàn', 'noun', 'sports', 'HSK 3'],
  ['游泳', 'yóuyǒng', 'Bơi lội', 'verb', 'sports', 'HSK 2'],
  ['跑步', 'pǎobù', 'Chạy bộ', 'verb', 'sports', 'HSK 2'],
  ['健身', 'jiànshēn', 'Tập gym, thể hình', 'verb', 'sports', 'HSK 4'],
  ['瑜伽', 'yújiā', 'Tập Yoga', 'noun', 'sports', 'HSK 4'],
  ['比赛', 'bǐsài', 'Trận đấu, thi đấu', 'noun', 'sports', 'HSK 3'],
  ['冠军', 'guànjūn', 'Nhà vô địch', 'noun', 'sports', 'HSK 4'],
  ['加油', 'jiāyóu', 'Cố lên!', 'verb', 'sports', 'HSK 3'],

  // 38. entertainment
  ['爱好', 'àihào', 'Sở thích', 'noun', 'entertainment', 'HSK 3'],
  ['周末聚会', 'zhōumò jùhuì', 'Tụ tập cuối tuần', 'noun', 'entertainment', 'HSK 3'],
  ['唱K', 'chàng K', 'Đi hát Karaoke', 'verb', 'entertainment', 'HSK 3'],
  ['逛街', 'guàngjiē', 'Dạo phố mua sắm', 'verb', 'entertainment', 'HSK 4'],
  ['露营', 'lùyíng', 'Cắm trại (Camping)', 'verb', 'entertainment', 'HSK 4'],
  ['野餐', 'yěcān', 'Dã ngoại (Picnic)', 'verb', 'entertainment', 'HSK 4'],
  ['摄影', 'shèyǐng', 'Nhiếp ảnh', 'noun', 'entertainment', 'HSK 4'],
  ['读书', 'dúshū', 'Đọc sách', 'verb', 'entertainment', 'HSK 2'],
  ['画画', 'huàhuà', 'Vẽ tranh', 'verb', 'entertainment', 'HSK 3'],
  ['放松', 'fàngsōng', 'Thư giãn, nghỉ ngơi', 'verb', 'entertainment', 'HSK 4'],

  // 39. movies
  ['电影', 'diànyǐng', 'Bộ phim điện ảnh', 'noun', 'movies', 'HSK 1'],
  ['电影院', 'diànyǐngyuàn', 'Rạp chiếu phim', 'noun', 'movies', 'HSK 2'],
  ['电视剧', 'diànshìjù', 'Phim truyền hình dài tập', 'noun', 'movies', 'HSK 3'],
  ['动画片', 'dònghuàpiàn', 'Phim hoạt hình', 'noun', 'movies', 'HSK 4'],
  ['纪录片', 'jìlùpiàn', 'Phim tài liệu', 'noun', 'movies', 'HSK 5'],
  ['演员', 'yǎnyuán', 'Diễn viên', 'noun', 'movies', 'HSK 4'],
  ['导演', 'dǎoyǎn', 'Đạo diễn', 'noun', 'movies', 'HSK 5'],
  ['字幕', 'zìmù', 'Phụ đề (Subtitle)', 'noun', 'movies', 'HSK 5'],
  ['票房', 'piàofáng', 'Doanh thu phòng vé', 'noun', 'movies', 'HSK 5'],
  ['剧情', 'jùqíng', 'Cốt truyện, tình tiết phim', 'noun', 'movies', 'HSK 5'],

  // 40. music
  ['音乐', 'yīnyuè', 'Âm nhạc', 'noun', 'music', 'HSK 3'],
  ['唱歌', 'chànggē', 'Ca hát', 'verb', 'music', 'HSK 2'],
  ['歌曲', 'gēqǔ', 'Bài hát, ca khúc', 'noun', 'music', 'HSK 3'],
  ['歌手', 'gēshǒu', 'Ca sĩ', 'noun', 'music', 'HSK 4'],
  ['演唱会', 'yǎnchànghuì', 'Buổi hòa nhạc (Concert)', 'noun', 'music', 'HSK 4'],
  ['吉他', 'jítā', 'Đàn Guitar', 'noun', 'music', 'HSK 4'],
  ['钢琴', 'gāngqín', 'Đàn Piano', 'noun', 'music', 'HSK 4'],
  ['旋律', 'xuánlǜ', 'Giai điệu', 'noun', 'music', 'HSK 5'],
  ['歌词', 'gēcí', 'Lời bài hát (Lyrics)', 'noun', 'music', 'HSK 4'],
  ['节奏', 'jiézòu', 'Nhịp điệu, tiết tấu', 'noun', 'music', 'HSK 5'],

  // 41. gaming
  ['游戏', 'yóuxì', 'Trò chơi (Game)', 'noun', 'gaming', 'HSK 3'],
  ['手游', 'shǒuyóu', 'Game di động (Mobile game)', 'noun', 'gaming', 'HSK 4'],
  ['电竞', 'diànjìng', 'Thể thao điện tử (eSports)', 'noun', 'gaming', 'HSK 5'],
  ['玩家', 'wánjiā', 'Người chơi (Game thủ)', 'noun', 'gaming', 'HSK 4'],
  ['组队', 'zǔduì', 'Lập đội chơi cùng', 'verb', 'gaming', 'HSK 4'],
  ['升级', 'shēngjí', 'Lên cấp (Level up)', 'verb', 'gaming', 'HSK 4'],
  ['皮肤', 'pífū', 'Trang phục tướng (Skin)', 'noun', 'gaming', 'HSK 4'],
  ['通关', 'tōngguān', 'Phá đảo, qua màn', 'verb', 'gaming', 'HSK 4'],
  ['挂机', 'guàjī', 'Treo máy (AFK)', 'verb', 'gaming', 'HSK 5'],
  ['装备', 'zhuāngbèi', 'Trang bị, vật phẩm', 'noun', 'gaming', 'HSK 5'],

  // 42. business
  ['生意', 'shēngyi', 'Kinh doanh, buôn bán', 'noun', 'business', 'HSK 4'],
  ['合作', 'hézuò', 'Hợp tác', 'verb', 'business', 'HSK 4'],
  ['客户', 'kèhù', 'Khách hàng, đối tác', 'noun', 'business', 'HSK 4'],
  ['谈判', 'tánpàn', 'Đàm phán, thương lượng', 'verb', 'business', 'HSK 5'],
  ['供应商', 'gōngyìngshāng', 'Nhà cung cấp (Supplier)', 'noun', 'business', 'HSK 5'],
  ['采购', 'cǎigòu', 'Thu mua (Purchasing)', 'verb', 'business', 'HSK 5'],
  ['进出口', 'jìnchūkǒu', 'Xuất nhập khẩu', 'noun', 'business', 'HSK 5'],
  ['物流', 'wùliú', 'Vận chuyển Logistics', 'noun', 'business', 'HSK 5'],
  ['报关', 'bàoguān', 'Khai báo hải quan', 'verb', 'business', 'HSK 5'],
  ['批发', 'pīfā', 'Bán sỉ, bán buôn', 'verb', 'business', 'HSK 5'],

  // 43. finance
  ['银行', 'yínháng', 'Ngân hàng', 'noun', 'finance', 'HSK 3'],
  ['人民币', 'Rénmínbì', 'Nhân dân tệ (RMB/CNY)', 'noun', 'finance', 'HSK 3'],
  ['越南盾', 'Yuènándùn', 'Việt Nam Đồng (VND)', 'noun', 'finance', 'HSK 3'],
  ['汇率', 'huìlǜ', 'Tỷ giá hối đoái', 'noun', 'finance', 'HSK 5'],
  ['转账', 'zhuǎnzhàng', 'Chuyển khoản', 'verb', 'finance', 'HSK 4'],
  ['投资', 'tóuzī', 'Đầu tư', 'verb', 'finance', 'HSK 5'],
  ['股票', 'gǔpiào', 'Cổ phiếu', 'noun', 'finance', 'HSK 5'],
  ['利润', 'lìrùn', 'Lợi nhuận', 'noun', 'finance', 'HSK 5'],
  ['成本', 'chéngběn', 'Chi phí, giá vốn', 'noun', 'finance', 'HSK 5'],
  ['预算', 'yùsuàn', 'Ngân sách', 'noun', 'finance', 'HSK 5'],

  // 44. marketing
  ['品牌', 'pǐnpái', 'Thương hiệu (Brand)', 'noun', 'marketing', 'HSK 4'],
  ['广告', 'guǎnggào', 'Quảng cáo', 'noun', 'marketing', 'HSK 4'],
  ['推广', 'tuīguǎng', 'Quảng bá, xúc tiến', 'verb', 'marketing', 'HSK 5'],
  ['促销', 'cùxiāo', 'Khuyến mãi', 'verb', 'marketing', 'HSK 5'],
  ['目标客户', 'mùbiāo kèhù', 'Khách hàng mục tiêu', 'noun', 'marketing', 'HSK 5'],
  ['转化率', 'zhuǎnhuàlǜ', 'Tỷ lệ chuyển đổi', 'noun', 'marketing', 'HSK 5'],
  ['流量池', 'liúliàngchí', 'Nguồn lưu lượng truy cập', 'noun', 'marketing', 'HSK 5'],
  ['爆款', 'bàokuǎn', 'Sản phẩm bán chạy (Best-seller)', 'noun', 'marketing', 'HSK 5'],
  ['口碑', 'kǒubēi', 'Danh tiếng truyền miệng', 'noun', 'marketing', 'HSK 5'],
  ['市场调研', 'shìchǎng diàoyán', 'Nghiên cứu thị trường', 'noun', 'marketing', 'HSK 5'],

  // 45. data_ai
  ['人工智能', 'réngōng zhìnéng', 'Trí tuệ nhân tạo (AI)', 'noun', 'data_ai', 'HSK 5'],
  ['大数据', 'dàshùjù', 'Dữ liệu lớn (Big Data)', 'noun', 'data_ai', 'HSK 5'],
  ['算法', 'suànfǎ', 'Thuật toán (Algorithm)', 'noun', 'data_ai', 'HSK 5'],
  ['大模型', 'dàmóxíng', 'Mô hình ngôn ngữ lớn (LLM)', 'noun', 'data_ai', 'HSK 6'],
  ['云计算', 'yúnjìsuàn', 'Điện toán đám mây', 'noun', 'data_ai', 'HSK 5'],
  ['自动化', 'zìdònghuà', 'Tự động hóa', 'noun', 'data_ai', 'HSK 5'],
  ['数据库', 'shùjùkù', 'Cơ sở dữ liệu (Database)', 'noun', 'data_ai', 'HSK 5'],
  ['代码', 'dàimǎ', 'Mã nguồn (Code)', 'noun', 'data_ai', 'HSK 5'],
  ['编程', 'biānchéng', 'Lập trình', 'verb', 'data_ai', 'HSK 5'],
  ['机器人', 'jīqìrén', 'Robot, người máy', 'noun', 'data_ai', 'HSK 4'],

  // 46. daily_actions
  ['起床', 'qǐchuáng', 'Thức dậy, rời giường', 'verb', 'daily_actions', 'HSK 2'],
  ['刷牙', 'shuāyá', 'Đánh răng', 'verb', 'daily_actions', 'HSK 3'],
  ['洗脸', 'xǐliǎn', 'Rửa mặt', 'verb', 'daily_actions', 'HSK 3'],
  ['洗澡', 'xǐzǎo', 'Tắm rửa', 'verb', 'daily_actions', 'HSK 3'],
  ['吃早饭', 'chī zǎofàn', 'Ăn sáng', 'verb', 'daily_actions', 'HSK 2'],
  ['做饭', 'zuòfàn', 'Nấu cơm', 'verb', 'daily_actions', 'HSK 2'],
  ['洗衣服', 'xǐ yīfu', 'Giặt quần áo', 'verb', 'daily_actions', 'HSK 2'],
  ['打扫', 'dǎsǎo', 'Dọn dẹp, quét dọn', 'verb', 'daily_actions', 'HSK 3'],
  ['散步', 'sànbù', 'Đi dạo bộ', 'verb', 'daily_actions', 'HSK 4'],
  ['睡觉', 'shuìjiào', 'Đi ngủ', 'verb', 'daily_actions', 'HSK 1'],

  // 47. common_verbs
  ['看', 'kàn', 'Nhìn, xem, đọc', 'verb', 'common_verbs', 'HSK 1'],
  ['听', 'tīng', 'Nghe', 'verb', 'common_verbs', 'HSK 1'],
  ['说', 'shuō', 'Nói', 'verb', 'common_verbs', 'HSK 1'],
  ['读', 'dú', 'Đọc', 'verb', 'common_verbs', 'HSK 1'],
  ['写', 'xiě', 'Viết', 'verb', 'common_verbs', 'HSK 1'],
  ['做', 'zuò', 'Làm', 'verb', 'common_verbs', 'HSK 1'],
  ['去', 'qù', 'Đi', 'verb', 'common_verbs', 'HSK 1'],
  ['来', 'lái', 'Đến', 'verb', 'common_verbs', 'HSK 1'],
  ['回', 'huí', 'Trở về', 'verb', 'common_verbs', 'HSK 1'],
  ['想', 'xiǎng', 'Muốn, nhớ, nghĩ', 'verb', 'common_verbs', 'HSK 1'],
  ['知道', 'zhīdào', 'Biết', 'verb', 'common_verbs', 'HSK 2'],
  ['觉得', 'juéde', 'Cảm thấy, cho rằng', 'verb', 'common_verbs', 'HSK 2'],
  ['希望', 'xīwàng', 'Hy vọng, mong muốn', 'verb', 'common_verbs', 'HSK 2'],
  ['帮助', 'bāngzhù', 'Giúp đỡ', 'verb', 'common_verbs', 'HSK 2'],
  ['准备', 'zhǔnbèi', 'Chuẩn bị', 'verb', 'common_verbs', 'HSK 2'],
  ['决定', 'juédìng', 'Quyết định', 'verb', 'common_verbs', 'HSK 3'],
  ['参加', 'cānjiā', 'Tham gia', 'verb', 'common_verbs', 'HSK 3'],
  ['解决', 'jiějué', 'Giải quyết', 'verb', 'common_verbs', 'HSK 3'],

  // 48. common_adjectives
  ['好', 'hǎo', 'Tốt, khỏe, hay', 'adjective', 'common_adjectives', 'HSK 1'],
  ['大', 'dà', 'To, lớn', 'adjective', 'common_adjectives', 'HSK 1'],
  ['小', 'xiǎo', 'Nhỏ, bé', 'adjective', 'common_adjectives', 'HSK 1'],
  ['多', 'duō', 'Nhiều', 'adjective', 'common_adjectives', 'HSK 1'],
  ['少', 'shǎo', 'Ít', 'adjective', 'common_adjectives', 'HSK 1'],
  ['快', 'kuài', 'Nhanh', 'adjective', 'common_adjectives', 'HSK 2'],
  ['慢', 'màn', 'Chậm', 'adjective', 'common_adjectives', 'HSK 2'],
  ['远', 'yuǎn', 'Xa', 'adjective', 'common_adjectives', 'HSK 2'],
  ['近', 'jìn', 'Gần', 'adjective', 'common_adjectives', 'HSK 2'],
  ['漂亮', 'piàoliang', 'Xinh đẹp', 'adjective', 'common_adjectives', 'HSK 1'],
  ['干净', 'gānjìng', 'Sạch sẽ', 'adjective', 'common_adjectives', 'HSK 3'],
  ['安静', 'ānjìng', 'Yên tĩnh', 'adjective', 'common_adjectives', 'HSK 3'],
  ['方便', 'fāngbiàn', 'Thuận tiện, tiện lợi', 'adjective', 'common_adjectives', 'HSK 3'],
  ['重要', 'zhòngyào', 'Quan trọng', 'adjective', 'common_adjectives', 'HSK 3'],
  ['简单', 'jiǎndān', 'Đơn giản', 'adjective', 'common_adjectives', 'HSK 3'],
  ['复杂', 'fùzá', 'Phức tạp', 'adjective', 'common_adjectives', 'HSK 4'],
  ['安全', 'ānquán', 'An toàn', 'adjective', 'common_adjectives', 'HSK 4'],
  ['精彩', 'jīngcǎi', 'Đặc sắc, tuyệt vời', 'adjective', 'common_adjectives', 'HSK 4'],

  // 49. adverbs
  ['也', 'yě', 'Cũng', 'adverb', 'adverbs', 'HSK 1'],
  ['都', 'dōu', 'Đều', 'adverb', 'adverbs', 'HSK 1'],
  ['已经', 'yǐjīng', 'Đã... rồi', 'adverb', 'adverbs', 'HSK 2'],
  ['正在', 'zhèngzài', 'Đang (diễn ra)', 'adverb', 'adverbs', 'HSK 2'],
  ['马上', 'mǎshàng', 'Ngay lập tức', 'adverb', 'adverbs', 'HSK 3'],
  ['突然', 'tūrán', 'Đột nhiên, bỗng nhiên', 'adverb', 'adverbs', 'HSK 3'],
  ['其实', 'qíshí', 'Thực ra, kỳ thực', 'adverb', 'adverbs', 'HSK 3'],
  ['果然', 'guǒrán', 'Quả nhiên, đúng như dự đoán', 'adverb', 'adverbs', 'HSK 4'],
  ['居然', 'jūrán', 'Không ngờ lại, thế mà lại', 'adverb', 'adverbs', 'HSK 4'],
  ['简直', 'jiǎnzhí', 'Quả thật là, chẳng khác nào', 'adverb', 'adverbs', 'HSK 5'],
  ['幸亏', 'xìngkuī', 'May mà, nhờ có', 'adverb', 'adverbs', 'HSK 5'],
  ['特意', 'tèyì', 'Cố ý, đặc biệt (làm gì)', 'adverb', 'adverbs', 'HSK 4'],

  // 50. conjunctions
  ['和', 'hé', 'Và, với', 'conjunction', 'conjunctions', 'HSK 1'],
  ['因为', 'yīnwèi', 'Bởi vì', 'conjunction', 'conjunctions', 'HSK 2'],
  ['所以', 'suǒyǐ', 'Cho nên', 'conjunction', 'conjunctions', 'HSK 2'],
  ['虽然', 'suīrán', 'Tuy rằng, mặc dù', 'conjunction', 'conjunctions', 'HSK 2'],
  ['但是', 'dànshì', 'Nhưng mà', 'conjunction', 'conjunctions', 'HSK 2'],
  ['如果', 'rúguǒ', 'Nếu như', 'conjunction', 'conjunctions', 'HSK 3'],
  ['而且', 'érqiě', 'Hơn nữa, mà còn', 'conjunction', 'conjunctions', 'HSK 3'],
  ['或者', 'huòzhě', 'Hoặc là (câu trần thuật)', 'conjunction', 'conjunctions', 'HSK 3'],
  ['还是', 'háishi', 'Hay là (câu hỏi lựa chọn)', 'conjunction', 'conjunctions', 'HSK 2'],
  ['只要', 'zhǐyào', 'Chỉ cần', 'conjunction', 'conjunctions', 'HSK 4'],
  ['无论', 'wúlùn', 'Bất luận, dù cho', 'conjunction', 'conjunctions', 'HSK 4'],
  ['否则', 'fǒuzé', 'Nếu không thì', 'conjunction', 'conjunctions', 'HSK 4'],

  // 51. prepositions
  ['在', 'zài', 'Ở, tại', 'preposition', 'prepositions', 'HSK 1'],
  ['从', 'cóng', 'Từ (thời gian/địa điểm)', 'preposition', 'prepositions', 'HSK 2'],
  ['向', 'xiàng', 'Hướng về, đối với', 'preposition', 'prepositions', 'HSK 3'],
  ['往', 'wǎng', 'Đi về phía', 'preposition', 'prepositions', 'HSK 2'],
  ['离', 'lí', 'Cách (khoảng cách/thời gian)', 'preposition', 'prepositions', 'HSK 2'],
  ['对', 'duì', 'Đối với', 'preposition', 'prepositions', 'HSK 2'],
  ['关于', 'guānyú', 'Về (chủ đề gì)', 'preposition', 'prepositions', 'HSK 3'],
  ['根据', 'gēnjù', 'Căn cứ theo, dựa vào', 'preposition', 'prepositions', 'HSK 3'],
  ['通过', 'tōngguò', 'Thông qua, qua', 'preposition', 'prepositions', 'HSK 4'],
  ['按照', 'ànzhào', 'Chiếu theo, làm theo', 'preposition', 'prepositions', 'HSK 4'],

  // 52. degree_words
  ['很', 'hěn', 'Rất', 'adverb', 'degree_words', 'HSK 1'],
  ['非常', 'fēicháng', 'Vô cùng, hết sức', 'adverb', 'degree_words', 'HSK 2'],
  ['太', 'tài', 'Quá, lắm', 'adverb', 'degree_words', 'HSK 1'],
  ['最', 'zuì', 'Nhất (so sánh bậc nhất)', 'adverb', 'degree_words', 'HSK 2'],
  ['更', 'gèng', 'Càng, hơn nữa', 'adverb', 'degree_words', 'HSK 3'],
  ['特别', 'tèbié', 'Đặc biệt, cực kỳ', 'adverb', 'degree_words', 'HSK 3'],
  ['相当', 'xiāngdāng', 'Khá là, tương đối', 'adverb', 'degree_words', 'HSK 4'],
  ['稍微', 'shāowēi', 'Hơi, một chút', 'adverb', 'degree_words', 'HSK 4'],
  ['极其', 'jíqí', 'Cực kỳ, vô cùng', 'adverb', 'degree_words', 'HSK 5'],
  ['越来越', 'yuèláiyuè', 'Càng ngày càng', 'adverb', 'degree_words', 'HSK 3'],

  // 53. time_words
  ['常常', 'chángcháng', 'Thường xuyên', 'adverb', 'time_words', 'HSK 2'],
  ['经常', 'jīngcháng', 'Thường, hay', 'adverb', 'time_words', 'HSK 3'],
  ['有时候', 'yǒushíhou', 'Có lúc, đôi khi', 'adverb', 'time_words', 'HSK 2'],
  ['偶尔', 'ǒu ěr', 'Thỉnh thoảng, đôi lúc', 'adverb', 'time_words', 'HSK 4'],
  ['从来', 'cónglái', 'Từ trước đến nay', 'adverb', 'time_words', 'HSK 4'],
  ['一直', 'yìzhí', 'Luôn luôn, suốt, một mạch', 'adverb', 'time_words', 'HSK 3'],
  ['永远', 'yǒngyuǎn', 'Mãi mãi', 'adverb', 'time_words', 'HSK 4'],
  ['暂时', 'zànshí', 'Tạm thời', 'noun', 'time_words', 'HSK 4'],
  ['刚才', 'gāngcái', 'Vừa nãy, mới lúc nãy', 'noun', 'time_words', 'HSK 3'],
  ['立刻', 'lìkè', 'Ngay tức khắc', 'adverb', 'time_words', 'HSK 4'],

  // 54. daily_expressions
  ['没问题', 'méi wèntí', 'Không thành vấn đề', 'phrase', 'daily_expressions', 'HSK 2'],
  ['算了吧', 'suàn le ba', 'Thôi bỏ đi, kệ đi', 'phrase', 'daily_expressions', 'HSK 3'],
  ['随便', 'suíbiàn', 'Tùy ý, sao cũng được', 'adjective', 'daily_expressions', 'HSK 4'],
  ['来不及', 'láibují', 'Không kịp nữa rồi', 'phrase', 'daily_expressions', 'HSK 4'],
  ['来得及', 'láidejí', 'Vẫn còn kịp', 'phrase', 'daily_expressions', 'HSK 4'],
  ['怪不得', 'guàibude', 'Thảo nào, hèn chi', 'phrase', 'daily_expressions', 'HSK 4'],
  ['说不定', 'shuōbudìng', 'Biết đâu chừng, có khi', 'phrase', 'daily_expressions', 'HSK 4'],
  ['开玩笑', 'kāi wánxiào', 'Nói đùa, trêu đùa', 'verb', 'daily_expressions', 'HSK 3'],
  ['看情况', 'kàn qíngkuàng', 'Tùy tình hình đã', 'phrase', 'daily_expressions', 'HSK 3'],
  ['保持联系', 'bǎochí liánxì', 'Giữ liên lạc nhé', 'phrase', 'daily_expressions', 'HSK 4'],

  // 55. slang
  ['牛逼', 'niúbī', 'Đỉnh của chóp, siêu giỏi', 'slang', 'slang', 'HSK 5'],
  ['内卷', 'nèijuǎn', 'Cạnh tranh kiệt sức (Involution)', 'slang', 'slang', 'HSK 5'],
  ['躺平', 'tǎngpíng', 'Nằm thẳng, buông xuôi áp lực', 'slang', 'slang', 'HSK 5'],
  ['摸鱼', 'mōyú', 'Lười biếng trốn việc giờ làm', 'slang', 'slang', 'HSK 5'],
  ['吃瓜', 'chīguā', 'Hóng biến, hóng drama', 'slang', 'slang', 'HSK 5'],
  ['种草', 'zhòngcǎo', 'Gây mê món đồ (muốn mua)', 'slang', 'slang', 'HSK 5'],
  ['拔草', 'bácǎo', 'Mua được đồ hoặc hết hứng mua', 'slang', 'slang', 'HSK 5'],
  ['显眼包', 'xiǎnyǎnbāo', 'Người thích thể hiện/nổi bật', 'slang', 'slang', 'HSK 5'],
  ['社牛', 'shèniú', 'Thánh ngoại giao (siêu hướng ngoại)', 'slang', 'slang', 'HSK 5'],
  ['社恐', 'shèkǒng', 'Sợ giao tiếp xã hội (hướng nội)', 'slang', 'slang', 'HSK 5'],
  ['破防', 'pòfáng', 'Chạm tới cảm xúc, vỡ òa', 'slang', 'slang', 'HSK 5'],
  ['凡尔赛', 'fán ěrsài', 'Khoe khéo (Flexing)', 'slang', 'slang', 'HSK 5'],

  // 56. common_phrases
  ['引人注目', 'yǐnrén zhùmù', 'Thu hút sự chú ý', 'phrase', 'common_phrases', 'HSK 5'],
  ['丰富多彩', 'fēngfù duōcǎi', 'Phong phú đa dạng', 'phrase', 'common_phrases', 'HSK 4'],
  ['成千上万', 'chéngqiān shàngwàn', 'Hàng ngàn hàng vạn', 'phrase', 'common_phrases', 'HSK 4'],
  ['不可思议', 'bùkě sīyì', 'Không thể tin nổi, kỳ diệu', 'phrase', 'common_phrases', 'HSK 5'],
  ['至关重要', 'zhìguān zhòngyào', 'Vô cùng quan trọng', 'phrase', 'common_phrases', 'HSK 5'],
  ['全力以赴', 'quánlì yǐfù', 'Dốc toàn lực thực hiện', 'phrase', 'common_phrases', 'HSK 5'],
  ['达成共识', 'dáchéng gòngshí', 'Đạt được sự đồng thuận', 'phrase', 'common_phrases', 'HSK 5'],
  ['脱颖而出', 'tuōyǐng érchū', 'Bứt phá nổi bật lên', 'phrase', 'common_phrases', 'HSK 6'],

  // 57. idioms
  ['入乡随俗', 'rùxiāng suísú', 'Nhập gia tùy tục', 'idiom', 'idioms', 'HSK 6'],
  ['半途而废', 'bàntú érfèi', 'Bỏ cuộc giữa chừng', 'idiom', 'idioms', 'HSK 5'],
  ['一举两得', 'yìjǔ liǎngdé', 'Một công đôi việc', 'idiom', 'idioms', 'HSK 5'],
  ['马马虎虎', 'mǎmǎhūhū', 'Bình thường, tàm tạm', 'idiom', 'idioms', 'HSK 4'],
  ['画蛇添足', 'huàshé tiānzú', 'Vẽ rắn thêm chân', 'idiom', 'idioms', 'HSK 6'],
  ['莫名其妙', 'mòmíng qímiào', 'Chẳng hiểu ra sao cả', 'idiom', 'idioms', 'HSK 5'],
  ['实事求是', 'shíshì qiúshì', 'Thực tế khách quan', 'idiom', 'idioms', 'HSK 6'],
  ['胸有成竹', 'xiōngyǒu chéngzhú', 'Nắm chắc phần thắng', 'idiom', 'idioms', 'HSK 6'],

  // 58. level_words
  ['可持续发展', 'kěchíxù fāzhǎn', 'Phát triển bền vững', 'noun', 'level_words', 'HSK 6'],
  ['全球化', 'quánqiúhuà', 'Toàn cầu hóa', 'noun', 'level_words', 'HSK 5'],
  ['基础设施', 'jīchǔ shèshī', 'Cơ sở hạ tầng', 'noun', 'level_words', 'HSK 5'],
  ['产业链', 'chǎnyèliàn', 'Chuỗi công nghiệp, chuỗi giá trị', 'noun', 'level_words', 'HSK 6'],
  ['核心竞争力', 'héxīn jìngzhēnglì', 'Năng lực cạnh tranh cốt lõi', 'noun', 'level_words', 'HSK 6'],
  ['知识产权', 'zhīshi chǎnquán', 'Quyền sở hữu trí tuệ', 'noun', 'level_words', 'HSK 6'],

  // 59. hsk_special
  ['不仅', 'bùjǐn', 'Không những', 'conjunction', 'hsk_special', 'HSK 3'],
  ['既然', 'jìrán', 'Đã... (thì)', 'conjunction', 'hsk_special', 'HSK 4'],
  ['哪怕', 'nǎpà', 'Cho dù, dù cho', 'conjunction', 'hsk_special', 'HSK 5'],
  ['何况', 'hékuàng', 'Huống hồ là', 'conjunction', 'hsk_special', 'HSK 5'],
  ['未免', 'wèimiǎn', 'E rằng hơi quá', 'adverb', 'hsk_special', 'HSK 6'],
  ['归根到底', 'guīgēn dàodǐ', 'Xét cho cùng, suy cho cùng', 'phrase', 'hsk_special', 'HSK 6'],

  // 60. vn_proficiency
  ['跨境电商', 'kuàjìng diànshāng', 'Thương mại điện tử xuyên biên giới', 'noun', 'vn_proficiency', 'HSK 5'],
  ['工业园区', 'gōngyè yuánqū', 'Khu công nghiệp (KCN)', 'noun', 'vn_proficiency', 'HSK 5'],
  ['双边贸易', 'shuāngbiān màoyì', 'Thương mại song phương Việt - Trung', 'noun', 'vn_proficiency', 'HSK 5'],
  ['供应链', 'gōngyìngliàn', 'Chuỗi cung ứng', 'noun', 'vn_proficiency', 'HSK 5'],
  ['清关手续', 'qīngguān shǒuxù', 'Thủ tục thông quan hải quan', 'noun', 'vn_proficiency', 'HSK 5'],
  ['外资企业', 'wàizī qǐyè', 'Doanh nghiệp FDI (vốn nước ngoài)', 'noun', 'vn_proficiency', 'HSK 5']
];

module.exports = { CORE_LEXICON };
