const fs = require('fs');
const path = require('path');

// ============================================================================
// 60 OFFICIAL TOPICS DEFINITION (BILINGUAL VI <-> ZH)
// ============================================================================
const TOPICS = [
  { id: 1, key: 'greetings', vi: '1. Chào hỏi & giao tiếp cơ bản', zh: '1. 问候与基础交际', level: 'HSK 1', cefr: 'A1' },
  { id: 2, key: 'pronouns', vi: '2. Đại từ nhân xưng', zh: '2. 人称代词与称谓', level: 'HSK 1', cefr: 'A1' },
  { id: 3, key: 'family', vi: '3. Gia đình', zh: '3. 家庭与亲属', level: 'HSK 1', cefr: 'A1' },
  { id: 4, key: 'people', vi: '4. Con người & nghề nghiệp', zh: '4. 人物与职业', level: 'HSK 1', cefr: 'A1' },
  { id: 5, key: 'numbers', vi: '5. Số đếm & định lượng', zh: '5. 数字与数量', level: 'HSK 1', cefr: 'A1' },
  { id: 6, key: 'time', vi: '6. Thời gian', zh: '6. 时间表达', level: 'HSK 1', cefr: 'A1' },
  { id: 7, key: 'dates', vi: '7. Ngày tháng & mùa', zh: '7. 日期与季节', level: 'HSK 1', cefr: 'A1' },
  { id: 8, key: 'colors', vi: '8. Màu sắc & hình khối', zh: '8. 颜色与形状', level: 'HSK 2', cefr: 'A1' },
  { id: 9, key: 'food', vi: '9. Đồ ăn & ẩm thực', zh: '9. 美食与食材', level: 'HSK 1', cefr: 'A1' },
  { id: 10, key: 'drinks', vi: '10. Đồ uống', zh: '10. 饮品与茶咖', level: 'HSK 1', cefr: 'A1' },
  { id: 11, key: 'restaurant', vi: '11. Nhà hàng & gọi món', zh: '11. 餐厅与点餐', level: 'HSK 2', cefr: 'A2' },
  { id: 12, key: 'shopping', vi: '12. Mua sắm & giá cả', zh: '12. 购物与砍价', level: 'HSK 2', cefr: 'A2' },
  { id: 13, key: 'clothing', vi: '13. Quần áo & phụ kiện', zh: '13. 服装与配饰', level: 'HSK 2', cefr: 'A2' },
  { id: 14, key: 'housing', vi: '14. Nhà cửa & bất động sản', zh: '14. 房屋与租房', level: 'HSK 2', cefr: 'A2' },
  { id: 15, key: 'household', vi: '15. Đồ dùng gia đình', zh: '15. 家居用品与家电', level: 'HSK 2', cefr: 'A2' },
  { id: 16, key: 'school', vi: '16. Trường học & giáo dục', zh: '16. 学校与教育', level: 'HSK 2', cefr: 'A2' },
  { id: 17, key: 'work', vi: '17. Công việc & sự nghiệp', zh: '17. 工作与职场', level: 'HSK 3', cefr: 'B1' },
  { id: 18, key: 'office', vi: '18. Văn phòng & hành chính', zh: '18. 办公与行政', level: 'HSK 3', cefr: 'B1' },
  { id: 19, key: 'technology', vi: '19. Công nghệ & phần cứng', zh: '19. 科技与数码', level: 'HSK 3', cefr: 'B1' },
  { id: 20, key: 'internet', vi: '20. Internet & mạng', zh: '20. 互联网与网站', level: 'HSK 3', cefr: 'B1' },
  { id: 21, key: 'phone', vi: '21. Điện thoại & viễn thông', zh: '21. 手机与通讯', level: 'HSK 2', cefr: 'A2' },
  { id: 22, key: 'social_media', vi: '22. Mạng xã hội & livestream', zh: '22. 社交媒体与直播', level: 'HSK 4', cefr: 'B1' },
  { id: 23, key: 'travel', vi: '23. Du lịch & khám phá', zh: '23. 旅游与观光', level: 'HSK 2', cefr: 'A2' },
  { id: 24, key: 'hotel', vi: '24. Khách sạn & lưu trú', zh: '24. 酒店与住宿', level: 'HSK 2', cefr: 'A2' },
  { id: 25, key: 'airport', vi: '25. Sân bay & hải quan', zh: '25. 机场与出入境', level: 'HSK 3', cefr: 'B1' },
  { id: 26, key: 'transport', vi: '26. Phương tiện giao thông', zh: '26. 交通工具与出行', level: 'HSK 2', cefr: 'A2' },
  { id: 27, key: 'city', vi: '27. Thành phố & đô thị', zh: '27. 城市与市政', level: 'HSK 3', cefr: 'A2' },
  { id: 28, key: 'places', vi: '28. Địa điểm & phương hướng', zh: '28. 场所与方位', level: 'HSK 2', cefr: 'A2' },
  { id: 29, key: 'health', vi: '29. Sức khỏe & bệnh viện', zh: '29. 健康与医疗', level: 'HSK 3', cefr: 'B1' },
  { id: 30, key: 'body', vi: '30. Cơ thể con người', zh: '30. 人体部位', level: 'HSK 2', cefr: 'A2' },
  { id: 31, key: 'emotions', vi: '31. Cảm xúc & tâm trạng', zh: '31. 情绪与感受', level: 'HSK 3', cefr: 'B1' },
  { id: 32, key: 'personality', vi: '32. Tính cách & phẩm chất', zh: '32. 性格与品质', level: 'HSK 4', cefr: 'B1' },
  { id: 33, key: 'nature', vi: '33. Thiên nhiên & môi trường', zh: '33. 自然与环境', level: 'HSK 3', cefr: 'B1' },
  { id: 34, key: 'weather', vi: '34. Thời tiết & khí hậu', zh: '34. 天气与气候', level: 'HSK 2', cefr: 'A2' },
  { id: 35, key: 'animals', vi: '35. Động vật', zh: '35. 动物世界', level: 'HSK 2', cefr: 'A2' },
  { id: 36, key: 'plants', vi: '36. Thực vật & hoa quả', zh: '36. 植物与蔬果', level: 'HSK 2', cefr: 'A2' },
  { id: 37, key: 'sports', vi: '37. Thể thao & rèn luyện', zh: '37. 体育与健身', level: 'HSK 2', cefr: 'A2' },
  { id: 38, key: 'entertainment', vi: '38. Giải trí & sở thích', zh: '38. 娱乐与爱好', level: 'HSK 3', cefr: 'B1' },
  { id: 39, key: 'movies', vi: '39. Phim ảnh & truyền hình', zh: '39. 电影与剧集', level: 'HSK 3', cefr: 'B1' },
  { id: 40, key: 'music', vi: '40. Âm nhạc & nghệ thuật', zh: '40. 音乐与艺术', level: 'HSK 3', cefr: 'B1' },
  { id: 41, key: 'gaming', vi: '41. Game & eSports', zh: '41. 游戏与电竞', level: 'HSK 4', cefr: 'B1' },
  { id: 42, key: 'business', vi: '42. Kinh doanh & thương mại', zh: '42. 商务与贸易', level: 'HSK 4', cefr: 'B2' },
  { id: 43, key: 'finance', vi: '43. Tài chính & ngân hàng', zh: '43. 金融与投资', level: 'HSK 4', cefr: 'B2' },
  { id: 44, key: 'marketing', vi: '44. Marketing & thương hiệu', zh: '44. 市场营销与品牌', level: 'HSK 5', cefr: 'B2' },
  { id: 45, key: 'data_ai', vi: '45. Data / AI / Công nghệ cao', zh: '45. 数据与人工智能', level: 'HSK 5', cefr: 'B2' },
  { id: 46, key: 'daily_actions', vi: '46. Hành động thường ngày', zh: '46. 日常起居动作', level: 'HSK 1', cefr: 'A1' },
  { id: 47, key: 'common_verbs', vi: '47. Động từ thông dụng', zh: '47. 高频核心动词', level: 'HSK 2', cefr: 'A2' },
  { id: 48, key: 'common_adjectives', vi: '48. Tính từ thông dụng', zh: '48. 高频核心形容词', level: 'HSK 2', cefr: 'A2' },
  { id: 49, key: 'adverbs', vi: '49. Trạng từ (Phó từ)', zh: '49. 常用副词', level: 'HSK 3', cefr: 'B1' },
  { id: 50, key: 'conjunctions', vi: '50. Liên từ nối câu', zh: '50. 关联词与连词', level: 'HSK 3', cefr: 'B1' },
  { id: 51, key: 'prepositions', vi: '51. Giới từ', zh: '51. 常用介词', level: 'HSK 3', cefr: 'B1' },
  { id: 52, key: 'degree_words', vi: '52. Từ chỉ mức độ', zh: '52. 程度表达词', level: 'HSK 2', cefr: 'A2' },
  { id: 53, key: 'time_words', vi: '53. Từ chỉ tần suất & thời điểm', zh: '53. 时间频率副词', level: 'HSK 2', cefr: 'A2' },
  { id: 54, key: 'daily_expressions', vi: '54. Từ giao tiếp đời thường', zh: '54. 地道口语交际', level: 'HSK 3', cefr: 'B1' },
  { id: 55, key: 'slang', vi: '55. Tiếng lóng & xu hướng giới trẻ', zh: '55. 流行语与网络热词', level: 'HSK 5', cefr: 'B2' },
  { id: 56, key: 'common_phrases', vi: '56. Các cụm từ thường gặp', zh: '56. 实用短语搭配', level: 'HSK 3', cefr: 'B1' },
  { id: 57, key: 'idioms', vi: '57. Thành ngữ & tục ngữ thông dụng', zh: '57. 成语与俗语', level: 'HSK 6', cefr: 'C1' },
  { id: 58, key: 'level_words', vi: '58. Từ vựng học thuật & nâng cao', zh: '58. 学术与进阶词汇', level: 'HSK 5', cefr: 'C1' },
  { id: 59, key: 'hsk_special', vi: '59. Từ vựng trọng điểm HSK 1–6', zh: '59. HSK核心考点词', level: 'HSK 4', cefr: 'B2' },
  { id: 60, key: 'vn_proficiency', vi: '60. Từ vựng giao tiếp Việt - Trung chuyên sâu', zh: '60. 越中跨境实务词汇', level: 'HSK 5', cefr: 'B2' }
];

module.exports = { TOPICS };
